[project]
name = "MyDroidApp"
version = "0.1"
main_file = "main.py"
target_platforms = [ "android",]
package_domain = "org.test"
build_type = "debug"

[android]
sdk_version = "36"
ndk_api = "24"
min_sdk_version = "24"
ndk_version = "28.2.13676358"
archs = [ "arm64-v8a", "armeabi-v7a",]
cmdline_tools_version = "13114758"
manifest_file = ""
intent_filters_file = ""
accept_sdk_license = "non-interactive"

[java]
jdk_version = "21"
gradle_version = "9.0.0"

[python]
python_version = "3.12.1"

[project.requirements]
python_packages = []
system_packages = []

[project.requirements.dependency_mapping]
# sdl2 = "https://github.com/libsdl-org/SDL/releases/download/release-3.2.22/SDL3-3.2.22.tar.gz"

[build]

[build.patches]
# sdl2 = ["sdl2-alooper.patch"]
