[app]
name = "MyAwesomeApp"
package_domain = "org.test"
version = "0.1"
root_dir = "."
main_file = "./main.py"
target_platforms = [ "android"]

[android]
cmdline_tools_version = "13114758"
sdk_version = "36"
ndk_version = "28.2.13676358"
min_sdk_version = "24"
ndk_api = "24"
archs = [ "arm64-v8a", "armeabi-v7a",]
manifest_file = ""
intent_filters_file = ""
accept_sdk_license = "non-interactive"

[java]
jdk_version = "21"
gradle_version = "9.0.0"

[python]
python_version = "3.12.1"

[app.dependency]
runtime_packages = ["kivy==2.3.1", "pyjnius"]
buildtime_packages = ["libffi==3.5.2", "openssl", "sdl2==2.32.2", "sdl2_ttf==2.24.0", "sdl2_mixer"]
patch_dir = "./patches"


[app.dependency_mapping]
libffi = "https://github.com/libffi/libffi/releases/download/v3.5.2/libffi-3.5.2.tar.gz"
openssl = "https://github.com/openssl/openssl/releases/download/openssl-3.6.0/openssl-3.6.0.tar.gz"
kivy = "https://github.com/kivy/kivy/archive/refs/tags/{version}.tar.gz"
sdl2 = "https://github.com/libsdl-org/SDL/releases/download/release-2.32.2/SDL2-2.32.2.tar.gz"
sdl2_ttf = "https://github.com/libsdl-org/SDL_ttf/releases/download/release-2.24.0/SDL2_ttf-2.24.0.tar.gz"
sdl2_mixer = "https://github.com/libsdl-org/SDL_mixer/releases/download/release-2.8.1/SDL2_mixer-2.8.1.tar.gz"

[build]
type = "debug"

[build.configure.arguments]
libffi = ["--disable-builddir",]
