[project]
name = "MyDroidApp"
version = "0.1"
main_file = "main.py"
target_platforms = [ "android",]
package_domain = "org.test"
build_type = "debug"

[requirements]
python_packages = []
system_packages = ["openssl==3.3.1", "xz==5.6.2", "openssl"]

[android]
sdk_version = "34"
ndk_version = "25.2.9519653"
min_sdk_version = "21"
ndk_api = "24"
archs = [ "arm64-v8a", "armeabi-v7a",]
cmdline_tools_version = "13114758"
manifest_file = ""
intent_filters_file = ""
accept_sdk_license = "non-interactive"

[java]
jdk_version = "11"
gradle_version = "8.7"

[python]
python_version = "3.12.1"
