[app]
name = "MyAwesomeApp"
package_domain = "org.test"
version = "0.1"
main_file = "main.py"
target_platforms = [ "android"]

[android]
cmdline_tools_version = "13114758"
sdk_version = "36"
ndk_version = "28.2.13676358"
min_sdk_version = "24"
ndk_api = "24"
archs = [ "arm64-v8a", "armeabi-v7a",]
manifest_file = ""
intent_filters_file = ""
accept_sdk_license = "interactive"

[java]
jdk_version = "21"
gradle_version = "9.0.0"

[python]
python_version = "3.12.1"

[app.dependency]
runtime_packages = []
buildtime_packages = ["libffi"]

[app.dependency_mapping]
libffi = "https://github.com/libffi/libffi/releases/download/v3.5.2/libffi-3.5.2.tar.gz"
openssl = "https://github.com/openssl/openssl/releases/download/openssl-3.6.0/openssl-3.6.0.tar.gz"

[build]
type = "debug"
