from .build import *
from .check_deps import *
from .clean import *
from .config import *
from .doctor import *
from .install import install # Explicitly import the install group
from .init import *
from .list_files import *
from .list_templates import *
from .list_tools import *
from .log import *
from .search_dependency import *
from .search_packages import *
from .search import *
from .uninstall import *
from .update_deps import *
from .update import *
from .version import *
from .search_code import *
from .grep import *
from .check_triplet import *
from .search_pkg import *